### PR TITLE
Replace cleanSelfLink with getResourceId

### LINKED ISSUE #1302: VolumeID is incorrect when project name contains beta
We created a GKE cluster in our project named xxxxx-beta and tried to create a statefulset with persistentvolume.

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard-rwo"
      resources:
        requests:
          storage: 10Gi
```

The PVC and PV were created and bound as expected, but the volume could not be attached to the pod due to the following reason:

AttachVolume.Attach failed for volume "pvc-c970f876-7563-4ef8-ad77-e1aafc02ff69" : rpc error: code = InvalidArgument desc = ControllerPublishVolume volume ID is invalid: failed to get id components. Expected projects/{project}/zones/{zone}/disks/{name}. Got: zones/asia-southeast1-c/disks/pvc-c970f876-7563-4ef8-ad77-e1aafc02ff69

GKE version: 1.27.2-gke.1200
pd-csi version: v1.10.3

### PR DESCRIPTION
**Pull request by mattcary**
/kind bug

Fixes #1302

```release-note
Fix resource parsing when the gcp project name ends with alpha, beta or v1
```

### CODE REVIEW

File: pkg/gce-pd-csi-driver/controller_test.go [hunk 1]
```diff
@@ -988,7 +992,11 @@ func TestListVolumeArgs(t *testing.T) {
 			var d []*gce.CloudDisk
 			for i := 0; i < diskCount; i++ {
 				// Create 600 dummy disks
-				d = append(d, gce.CloudDiskFromV1(&compute.Disk{Name: fmt.Sprintf("%v", i)}))
+				name := fmt.Sprintf("disk-%v", i)
+				d = append(d, gce.CloudDiskFromV1(&compute.Disk{
+					Name:     name,
+					SelfLink: fmt.Sprintf("https://www.googleapis.com/compute/v1/projects/project/zone/zone/disk/%s", name),
```
Comment (sunnylovestiramisu) [inline pkg/gce-pd-csi-driver/controller_test.go:998]: Shouldn't it be projects/project/**zones**/zone ?

Comment (mattcary) [reply pkg/gce-pd-csi-driver/controller_test.go:998]: ah, thanks. That's not causing the tests to fail though, since we don't validate that part of the resource (there are many options for that---regional, global, ...?

File: pkg/gce-pd-csi-driver/controller_test.go [hunk 2]
```diff
@@ -3304,13 +3313,61 @@ func TestCleanSelfLink(t *testing.T) {
 			in:   "https://www.partnerapis.com/compute/alpha/projects/project/zones/zone/disks/disk",
 			want: "projects/project/zones/zone/disks/disk",
 		},
+		{
+			name: "alpha project",
+			in:   "https://www.googleapis.com/compute/alpha/projects/alphaproject/zones/zone/disks/disk",
```
Comment (judemars) [inline pkg/gce-pd-csi-driver/controller_test.go:3318]: Nit: another nice test would be something like project name = betabeta

File: pkg/gce-pd-csi-driver/controller_test.go [hunk 3]
```diff
@@ -3304,13 +3313,61 @@ func TestCleanSelfLink(t *testing.T) {
...
+			in:    "https://www.googleapis.com/computers/v1/projects/project/zones/zone/disks/disk",
+			error: true,
+		},
+		{
+			name:  "bad host",
+			in:    "https://compute.googleapis.com/compute/v1/projects/project/zones/zone/disks/disk",
+			error: true,
+		},
+		{
+			name:  "bad version",
```
Comment (judemars) [inline pkg/gce-pd-csi-driver/controller_test.go:3352]: Let's add a few more test cases:

content-compute.googleapis.com

compute.blahapis.com

content-compute.us-central1.rep.mtls.googleapis.com

File: pkg/gce-pd-csi-driver/controller_test.go (hunk 2 above)
Comment (mattcary) [reply pkg/gce-pd-csi-driver/controller_test.go:3318]: done

File: pkg/gce-pd-csi-driver/controller_test.go (hunk 3 above)
Comment (mattcary) [reply pkg/gce-pd-csi-driver/controller_test.go:3352]: done

**Review by judemars — APPROVED** [review]

**Comment by mattcary** [comment]
/retest

Looking at history the job time has been ~18m, and this has also picked up the fsck change which may have increased the run time a bit. We may just need to increase the timeout on the test.

**Comment by mattcary** [comment]
Manually created #1308 for release-1.9 cherry-pick.

1.8 is not affected.
