### PR TITLE
Make a clone of k8s master instead of using archive

### LINKED ISSUE #721: GCE cluster up is failing for k8s-integration tests on k/k master.
The symptom is that the e2e-up called from the k8s-integration test on k/k master will hang on waiting for nodes to be ready. Node kubelet logs contain an error like the following. 

```
cannot create certificate signing request: certificatesigningrequests.certificates.k8s.io is forbidden: User "kubelet" cannot create resource "certificatesigningrequests" in API group "certificates.k8s.io" at the cluster scope.
```

And there are additional errors in the kube-addon-manager.log as well.

It appears that the 888.888 git version used in test/k8s-integration/.dockerized-kube-version-defs causes something critical to get removed or not activated, although I haven't been able to figure out what.

This can be temporarily fixed by setting the version there to 1.21+. It would be better to automatically infer the kube version, maybe there is some trickery to be done, or maybe it would be easiest to clone from git rather than just downloading the archive.

### PR DESCRIPTION
**Pull request by mattcary**
/kind bug

**Which issue(s) this PR fixes**:
Fixes #721 

**Special notes for your reviewer**:
This is a more complete change compare with #722.

See the comment in the change for the details of how the git clone is done for the master branch.

Pulling a specific version is unchanged (the k/k release archive is still used).
**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: test/k8s-integration/cluster.go [hunk 1]
```diff
@@ -206,57 +206,46 @@ func clusterUpGKE(gceZone, gceRegion string, numNodes int, imageType string, use
...
 	}
 
-	kubeTarDir := filepath.Join(k8sIoDir, fmt.Sprintf("kubernetes-%s.tar.gz", kubeVersion))
-
-	var vKubeVersion string
 	if kubeVersion == "master" {
-		vKubeVersion = kubeVersion
-		// A hack to be able to build Kubernetes in this nested place
-		// KUBE_GIT_VERSION_FILE set to file to load kube version from
-		err = os.Setenv("KUBE_GIT_VERSION_FILE", filepath.Join(pkgDir, "test", "k8s-integration", ".dockerized-kube-version-defs"))
```
Comment (saikat-royc) [inline test/k8s-integration/cluster.go:231]: Should we also remove dockerized-kube-version-defs file if its not needed now?

**Comment by saikat-royc** [comment]
the change looks good to me, with some minor comment

File: test/k8s-integration/cluster.go (hunk 1 above)
Comment (mattcary) [reply test/k8s-integration/cluster.go:231]: I did remove it :-)

Comment (saikat-royc) [reply test/k8s-integration/cluster.go:231]: oops missed it
