### PR TITLE
bugfix-222 Driver should check socket parent directory before trying …

### LINKED ISSUE #222: Driver should check socket parent directory before trying to bind it
While testing the driver, we found that in the server's code https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/gce-pd-csi-driver/server.go#L85,  if the socket parent directory does not exit, the driver does not check it and just tries to call Listen to the address. So the error message returned from Listen call does not give the clear reason why it fail. It would be better to check whether the parent directory exist or not before listening to the socket address.

### PR DESCRIPTION
**Pull request by zhucan**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
if the socket parent directory does not exit, the driver does not check it and just tries to call Listen to the address. So the error message returned from Listen call does not give the clear reason why it fail. It would be better to check whether the parent directory exist or not before listening to the socket address.

**Which issue(s) this PR fixes**:

Fixes #222

**Special notes for your reviewer**:
@jingxu97 
@davidz627 

**Does this PR introduce a user-facing change?**:

```release-note
Driver should check socket parent directory before trying to bind it
```

### CODE REVIEW

File: pkg/gce-pd-csi-driver/server.go [hunk 1]
```diff
@@ -92,6 +93,13 @@ func (s *nonBlockingGRPCServer) serve(endpoint string, ids csi.IdentityServer, c
 		klog.Fatalf("%v endpoint scheme not supported", u.Scheme)
 	}
 
+	if u.Scheme == "unix" {
```
Comment (davidz627) [inline pkg/gce-pd-csi-driver/server.go]: could this just be moved into the same `if u.Scheme == "unix"` block above

File: pkg/gce-pd-csi-driver/server.go [hunk 2]
```diff
@@ -92,6 +93,13 @@ func (s *nonBlockingGRPCServer) serve(endpoint string, ids csi.IdentityServer, c
...
+		listenDir, _ := filepath.Split(addr)
```
Comment (davidz627) [inline pkg/gce-pd-csi-driver/server.go]: `filepath.Dir` could be better here since you drop the last output anyway

File: pkg/gce-pd-csi-driver/server.go [hunk 3]
```diff
@@ -92,6 +93,13 @@ func (s *nonBlockingGRPCServer) serve(endpoint string, ids csi.IdentityServer, c
...
+		if _, err := os.Stat(listenDir); err != nil {
```
Comment (davidz627) [inline pkg/gce-pd-csi-driver/server.go]: would prefer a check for an `os.IsNotExist(err)` explicitly and the error message thrown could be more illuminating such as: "Expected Kubelet plugin watcher to create parent dir *dirname* but did not find such a di"

**Comment by zhucan** [comment]
> thanks for picking this up @zhucan! Just some minor comments, feel free to chat on slack (i'm davidz627) if you have any questions

copy that, thanks

**Comment by davidz627** [comment]
Thanks @zhucan
