### PR TITLE
Update VerifyDevicePath logic to run udevadm --trigger to fix scenarios where disk is not found or is wrong device

### LINKED ISSUE #376: udevadm may be never triggered right now
In the function `VerifyDevicePath`(https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/mount-manager/device-utils.go#L89), the value of `sdBefore` is the same with `sdAfter`. 

Then the function `udevadmChangeToDrive` will never be called. It seems like the code doesn't actually do anything. 

/ping @davidz627

### PR DESCRIPTION
**Pull request by davidz627**
TODO:
- [x] Write an E2E test that tests this functionality: attaches disk -> purposely links the `/dev/by-id/{diskName}` to the wrong device or deletes the `/dev/by-id/{diskName}` entirely then make sure `NodeStage` is able to self-heal that using `udevadm --trigger`

/kind bug
/assign @msau42 
Fixes #376 

`/lib/udev/scsi_id` was pointing to the binary on the host due to the `/lib/udev` hostPath. This was causing weird package dynamically linked library finding issues (couldn't find the right version of dynamic libs). The solution is to use the `/lib/udev/scsi_id` from the container by copying it into a special directory. Thanks @msau42 for pointing out that `/lib/udev` was coming from the host

ig9OoyenpxqdCQyABmOQBZDI0duHk2QZZmWg2Hxd4ro

```release-note
During NodeStageVolume run udevadm --trigger to fix device symlinks if device path is not found or device path points to the wrong device
```

### CODE REVIEW

**Comment by davidz627** [comment]
Wrote the e2e test and confirmed its failing before the `udevadm` logic fix, and passes afterwards :)

File: test/e2e/utils/utils.go [hunk 1]
```diff
@@ -49,8 +49,8 @@ func GCEClientAndDriverSetup(instance *remote.InstanceInfo) (*remote.TestContext
 	endpoint := fmt.Sprintf("tcp://localhost:%s", port)
 
 	workspace := remote.NewWorkspaceDir("gce-pd-e2e-")
-	driverRunCmd := fmt.Sprintf("sh -c '/usr/bin/nohup %s/gce-pd-csi-driver --endpoint=%s> %s/prog.out 2> %s/prog.err < /dev/null &'",
-		workspace, endpoint, workspace, workspace)
+	driverRunCmd := fmt.Sprintf("sh -c '/usr/bin/nohup %s/gce-pd-csi-driver -v=4 --endpoint=%s 2> %s/prog.out < /dev/null > /dev/null &'",
```
Comment (davidz627) [inline test/e2e/utils/utils.go]: small fix to improve debugging experience. This is on purpose

File: cmd/main.go [hunk 2]
```diff
@@ -28,10 +28,6 @@ import (
 	mountmanager "sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/pkg/mount-manager"
 )
 
-func init() {
```
Comment (davidz627) [inline cmd/main.go]: we had two init functions before, I don't know if that was causing issues but it doesn't hurt to fix

File: test/e2e/tests/single_zone_e2e_test.go [hunk 3]
```diff
@@ -81,7 +84,69 @@ var _ = Describe("GCE PD CSI Driver", func() {
...
+			err = client.ControllerUnpublishVolume(volID, instance.GetNodeID())
+			if err != nil {
+				klog.Errorf("Failed to detach disk: %v", err)
+			}
+
+		}()
 
+		// MESS UP THE symlink
+
+		err = testutils.RmAll(instance, "/dev/disk/by-id")
```
Comment (davidz627) [inline test/e2e/tests/single_zone_e2e_test.go]: this only tests the "symlink not found" path, need to augment test to also switch symlinks around and test that as well.

File: pkg/mount-manager/device-utils.go [hunk 4]
```diff
@@ -85,75 +95,146 @@ func (m *deviceUtils) GetDiskByIdPaths(deviceName string, partition string) []st
...
-			return udevadmChangeToDrive(sd)
+	scsiIDPath := "/lib/udev_containerized/scsi_id"
+	exists, err := pathutils.Exists(pathutils.CheckFollowSymlink, scsiIDPath)
+	if err != nil {
+		return "", fmt.Errorf("failed to check scsi_id existence: %v", err)
+	}
+	if !exists {
+		// No SCSI ID tool, no udevadm fixing is possible so just return best
+		// effort devicePath.
+		klog.Warningf("Could not find scsi_id tool at %s, no udevadm fixing is possible so we just return the best effort devicePath", scsiIDPath)
```
Comment (msau42) [inline pkg/mount-manager/device-utils.go]: Should we make it required? I'm worried that if there's an issue in our container build process that doesn't install it properly, then this problem will go undetected.

File: test/e2e/tests/single_zone_e2e_test.go [hunk 5]
```diff
@@ -81,7 +84,68 @@ var _ = Describe("GCE PD CSI Driver", func() {
...
+			// Detach Disk
+			err = client.ControllerUnpublishVolume(volID, instance.GetNodeID())
+			if err != nil {
+				klog.Errorf("Failed to detach disk: %v", err)
+			}
+
+		}()
+
+		// MESS UP THE symlink
+		err = testutils.RmAll(instance, "/dev/disk/by-id")
```
Comment (msau42) [inline test/e2e/tests/single_zone_e2e_test.go]: This has the potential to be incredibly destructive if you run the test locally or not on some throwaway machine. Prefer only touching the specific disk that the test is using.

File: test/e2e/tests/single_zone_e2e_test.go [hunk 6]
```diff
@@ -81,7 +84,68 @@ var _ = Describe("GCE PD CSI Driver", func() {
...
+		Expect(err).To(BeNil(), "failed to remove /dev/by-id folder")
+
+		// Stage Disk
+		stageDir := filepath.Join("/tmp/", volName, "stage")
+		err = client.NodeStageExt4Volume(volID, stageDir)
+		Expect(err).To(BeNil(), "failed to repair /dev/by-id symlink and stage volume")
```
Comment (msau42) [inline test/e2e/tests/single_zone_e2e_test.go]: Can we also validate the link is correct?

Comment (msau42) [reply test/e2e/tests/single_zone_e2e_test.go]: Or do something like write data to it, and then validate the data is correct

File: test/e2e/tests/single_zone_e2e_test.go (hunk 5 above)
Comment (davidz627) [reply test/e2e/tests/single_zone_e2e_test.go]: haha oops you're right. that's still pretty risky to be honest but far less so

File: pkg/mount-manager/device-utils.go [hunk 7]
```diff
@@ -85,75 +95,146 @@ func (m *deviceUtils) GetDiskByIdPaths(deviceName string, partition string) []st
...
-// --action=change" for newly created "/dev/sd*" drives (exist only in
-// after set). This is workaround for Issue #7972. Once the underlying
-// issue has been resolved, this may be removed.
-func udevadmChangeToNewDrives(sdBeforeSet sets.String) error {
-	sdAfter, err := filepath.Glob(diskSDPattern)
+// VerifyDevicePath returns the first devicePath that maps to a real disk in the
+// candidate devicePaths or an empty string if none is found. If
+// /lib/udev/scsi_id exists it will attempt to fix any issues caused by missing
+// paths or mismatched devices by running a udevadm --trigger.
+func (m *deviceUtils) VerifyDevicePath(devicePaths []string, diskName string) (string, error) {
```
[the remark this answers is not in the document]
Comment (davidz627) [reply pkg/mount-manager/device-utils.go]: I guess we don't really have to, but then we would need to add partition as an argument. (I can follow up but probably out of scope for this PR)

File: pkg/mount-manager/device-utils.go (hunk 4 above)
Comment (davidz627) [reply pkg/mount-manager/device-utils.go]: yeah, you're right. Since this is containerized it does make sense that it should always exist. If not it's definitely a problem.

File: test/e2e/tests/single_zone_e2e_test.go (hunk 6 above)
Comment (davidz627) [reply test/e2e/tests/single_zone_e2e_test.go]: added some validation logic that goes and checks which disk is actually backing a link

File: pkg/mount-manager/device-utils.go [hunk 8]
```diff
@@ -85,75 +96,166 @@ func (m *deviceUtils) GetDiskByIdPaths(deviceName string, partition string) []st
...
+	scsiIDPath := "/lib/udev_containerized/scsi_id"
+	exists, err := pathutils.Exists(pathutils.CheckFollowSymlink, scsiIDPath)
 	if err != nil {
-		return fmt.Errorf("Error filepath.Glob(\"%s\"): %v\r\n", diskSDPattern, err)
+		return "", fmt.Errorf("failed to check scsi_id existence: %v", err)
+	}
+	if !exists {
+		// No SCSI ID tool, the driver should be containerized with the tool so
+		// maybe something is wrong with the build process
+		return "", fmt.Errorf("could not find scsi_id tool at %s, no udevadm fixing is possible so we just return the best effort devicePath", scsiIDPath)
```
Comment (msau42) [inline pkg/mount-manager/device-utils.go]: error message is out of date?

File: pkg/mount-manager/device-utils.go [hunk 9]
```diff
@@ -85,75 +96,166 @@ func (m *deviceUtils) GetDiskByIdPaths(deviceName string, partition string) []st
...
 	}
 
-	for _, sd := range sdAfter {
-		if !sdBeforeSet.Has(sd) {
-			return udevadmChangeToDrive(sd)
+	err = wait.Poll(pollInterval, pollTimeout, func() (bool, error) {
+		var innerErr error
+
+		devicePath, innerErr = existingDevicePath(devicePaths)
```
Comment (msau42) [inline pkg/mount-manager/device-utils.go]: We don't regenerate `devicePaths` on the next loop, so would this still fail?

File: pkg/mount-manager/device-utils.go [hunk 10]
```diff
@@ -85,75 +96,166 @@ func (m *deviceUtils) GetDiskByIdPaths(deviceName string, partition string) []st
...
 		"trigger",
 		"--action=change",
-		fmt.Sprintf("--property-match=DEVNAME=%s", drive)).CombinedOutput()
+		fmt.Sprintf("--property-match=DEVNAME=%s", devSDX)).CombinedOutput()
 	if err != nil {
-		return fmt.Errorf("udevadmChangeToDrive: udevadm trigger failed for drive %q with %v.", drive, err)
+		return fmt.Errorf("udevadmChangeToDrive: udevadm trigger failed for drive %q with output %s: %v.", devSDX, string(out), err)
 	}
+
+	time.Sleep(time.Second)
```
Comment (msau42) [inline pkg/mount-manager/device-utils.go]: Since this is inside a Poll loop now, do we still need this sleep?

File: test/e2e/tests/single_zone_e2e_test.go [hunk 11]
```diff
@@ -81,7 +85,78 @@ var _ = Describe("GCE PD CSI Driver", func() {
...
+			if err != nil {
+				klog.Errorf("Failed to detach disk: %v", err)
+			}
+
+		}()
+
+		// MESS UP THE symlink
+		devicePaths := mountmanager.NewDeviceUtils().GetDiskByIdPaths(volName, "")
+		for _, devicePath := range devicePaths {
+			err = testutils.RmAll(instance, devicePath)
```
Comment (msau42) [inline test/e2e/tests/single_zone_e2e_test.go]: Is this still going to be potentially destructive if volume name is a prefix of an existing disk? ie, volume name is "foo" but a real disk is called "foobar"

File: test/e2e/utils/utils.go [hunk 12]
```diff
@@ -195,10 +196,69 @@ func GetBlockSizeInGb(instance *remote.InstanceInfo, devicePath string) (int64,
...
+func CopyFile(instance *remote.InstanceInfo, src, dest string) error {
+	output, err := instance.SSH("cp", src, dest)
+	if err != nil {
+		return fmt.Errorf("failed to copy %s to %s. Output: %v, errror: %v", src, dest, output, err)
+	}
+	return nil
+}
+
+// ValidateLogicalLinkIsDisk takes a symlink location at "link" and finds the
+// link location - it then finds the backing PD using scsi_id and validates that
```
Comment (msau42) [inline test/e2e/utils/utils.go]: This is fine for now, although when NVMe comes up, this test will get outdated. I think writing data and verifying it would be more portable.

Comment (davidz627) [reply test/e2e/utils/utils.go]: The thing is writing data would work if the symlink was made incorrectly, so I'm not sure it validates what we care about. (Which is that the volume matches the device). Writing this check was much harder than writing data :)

I don't think network attached PD supports NVME. Only available for local ssd

File: pkg/mount-manager/device-utils.go (hunk 10 above)
Comment (davidz627) [reply pkg/mount-manager/device-utils.go]: Not sure why this is still here. Thought I removed it, fixing

File: pkg/mount-manager/device-utils.go (hunk 9 above)
Comment (davidz627) [reply pkg/mount-manager/device-utils.go]: DevicePaths are a list of all possible device paths generated from a pattern, the existingdevicepath one is checking which of those are present on disk. So this essentially "regenerate" the new device pah if it exists now

File: test/e2e/tests/single_zone_e2e_test.go (hunk 11 above)
Comment (davidz627) [reply test/e2e/tests/single_zone_e2e_test.go]: I don't think so. The device paths are full absolute paths.

We're doing a:
`rm -rf /dev/disk/by-id/foo`
which wont affect:
`/dev/disk/by-id/foobar`

File: test/e2e/utils/utils.go (hunk 12 above)
Comment (msau42) [reply test/e2e/utils/utils.go]: Yes, there's no NVME for PD now, I'm just saying for future proofing.

File: pkg/mount-manager/device-utils.go (hunk 9 above)
Comment (msau42) [reply pkg/mount-manager/device-utils.go]: Thanks, I understand now
